-- Extend ChatRoomType enum with DIRECT, GROUP, AGENCY_CHANNEL
ALTER TYPE "ChatRoomType" ADD VALUE IF NOT EXISTS 'DIRECT';
ALTER TYPE "ChatRoomType" ADD VALUE IF NOT EXISTS 'GROUP';
ALTER TYPE "ChatRoomType" ADD VALUE IF NOT EXISTS 'AGENCY_CHANNEL';

-- Extend ChatMessageType enum with VOICE
ALTER TYPE "ChatMessageType" ADD VALUE IF NOT EXISTS 'VOICE';
